name: SWE-agent
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, synchronize]
  discussion:
    types: [created, edited]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
      discussions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'

      - name: Run SWE-agent
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-path: config/github.yaml
          target-hourly-cost: '10.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYTHONPATH: ${{ github.workspace }}

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: swe-agent-logs
          path: logs/github.log
          retention-days: 7
